### ISSUE TITLE
Recent return code change seems to have broken MMA8451 library.

### ISSUE THREAD

**Issue by TheNorm95010** [adafruit/Adafruit_MMA8451_Library#4]
Error message...

In file included from MMA8451demo.cpp:21:0:
/home/pi/sketchbook/libraries/Adafruit_MMA8451_Library_master/Adafruit_MMA8451.h:93:8: error: conflicting return type specified for ‘virtual bool Adafruit_MMA8451::getEvent(sensors_event_t_)’
In file included from /home/pi/sketchbook/libraries/Adafruit_MMA8451_Library_master/Adafruit_MMA8451.h:27:0,
                 from MMA8451demo.cpp:21:
/home/pi/sketchbook/libraries/Adafruit_Sensor_master/Adafruit_Sensor.h:146:16: error:   overriding ‘virtual void Adafruit_Sensor::getEvent(sensors_event_t_)’

**Comment by microbuilder** [comment]
You need to update to the latest version of the Adafruit_Sensor and Adafruit_MMS8451_Library repos since we recently had to make a breaking change to this function.  All of the public libraries have been modified, but one or more of your local instances it probably out of date.  Sorry for the trouble, but it was an important change to improve the reliability of the sensor data.
